# Let's make signal.mat

In [ ]:
'''LFM 펄스 레이다 신호 생성 시뮬레이션'''


import numpy as np
import random
import scipy.io
from scipy.constants import speed_of_light, pi

# raw data에 azimuth reference function이 적용되었는지에 따라
# 실제 실험 환경 또는 azi ref이 적용된 raw data = 'azref'
# 단일 타겟 azi ref이 적용되지 않은 raw data = 'one_target_no_azref'
# 다중 타겟 azi ref이 적용되지 않은 raw data = 'many_targets_no_azref'
fig39 = 'one_target_no_azref'

nAz = 2676  # Azimuth samples
nRange = 48  # Range samples
aperture_length = 200  # Synthetic Aperture Length
bandwidth = 100e6  # Bandwidth (Hz)
synthetic_aperture = np.linspace(-aperture_length / 2, aperture_length / 2, nAz)
prf = 850  # Pulse Repetition Frequency (Hz)
range_center = np.full((1, 2676), 10000)
rc = 10000
fc = (9.95e9 + 10.05e9) / 2
wavelength = speed_of_light / fc
slow_time = np.linspace(-prf / 2, prf / 2, nAz)
vel = 100  # Target velocity (m/s)

range_freqs = np.linspace(9.95e9, 10.05e9, nRange)
slant = np.linspace(0, 10000, nRange)  # Slant ranges

sar_raw_data = np.zeros((nAz, nRange), dtype=complex)

t_cross_range = -5
t_range = -20

# 타겟 반사 신호 생성 (주파수 도메인에서)

target_az = t_cross_range                    # target의 cross_range 방향 위치: 5 m
target_range = range_center[0, 0] + t_range  # range_center + range 방향 위치: 10000 + 20 = 10020 m


# 각 플랫폼(azimuth) 위치에서 타겟과의 거리, 지연 시간을 이용해서 단일 타겟에 대한 반사 신호 생성
# Azimuth reference function이 적용되지 않음
for i, platform_x in enumerate(synthetic_aperture):
    
    # 플랫폼 위치: (platform_x, 0), 타겟 위치: (target_az, target_range)
    R = np.sqrt((target_range)**2 + (platform_x - target_az)**2)
    
    # 지연 시간
    tau = 2 * R / speed_of_light # -> back projection 코드에서 신호 생성하는거 확인하기
    
    # range_freqs 벡터에 해당하는 하나의 chirp신호를 플랙폼의 이동에 따라 변화하는 tau 항을 통해 반사 신호 생성:
    sar_raw_data[i, :] = np.exp(-1j * 2 * pi * range_freqs * tau)
    
print(sar_raw_data.shape)

# 데이터 저장
data = {
    'signal': sar_raw_data,
    'frequency': range_freqs,
    'range_center': range_center,
    'synthetic_aperture': synthetic_aperture,
    'aperture_length': aperture_length,
    'bandwidth': bandwidth,
    'fig39': fig39,
    'target_az': target_az
}

scipy.io.savemat('sar_raw_data.mat', data)

(2676, 48)


In [ ]:
'''FMCW 레이다 신호 생성 시뮬레이션'''

(2676, 48)


In [51]:
# Quick wxamples of append numpy arrays

# Example 1: Creating a 1D NumPy array 
# From a Python list
my_list = [0, 2, 4, 6, 8]
result1 = np.array(my_list)
print(result1)
print('\n')
# Example 2: Create 2D numpy array 
# Using numpy.array() method
my_list = [[0,2,4],[6,8,10]]
result2 = np.array(my_list) 
print(result2)
print('\n')
# Example 3: Use numpy.append() function
arr = np.array([0,2,4,6,8,10]) 
result3 = np.append(arr, [13,15,17]) 
print(result3)
print('\n')
# Example 4: Appending arrays 
# Along axis=0 (stacking vertically)
arr = np.array([0, 1, 3])
arr1 = np.array([5, 7, 9])
result4 = np.append(arr, arr1, axis=0)
print(result4)
print('\n')
# Example 5: Creating two 2D NumPy arrays
arr = np.array([[0,2,4],[6,8,10]]) 
result5 = np.append(arr, [[5,7,9]],axis = 0)
print(result5)
print('\n')
# Example 6: Appending arrays 
# Along axis=1 (stacking horizontally)
arr = np.array([[0,2,4],[6,8,10]]) 
result6 = np.append(arr, [[5,7,9],[13,15,17]],axis = 1) 
print(result6)
print('\n')
# Example 7: Use arange() Function 
# To Append an Array
array = np.arange(1, 6)  
array1 = np.array([6, 7, 8, 9, 10])
result7 = np.append(array, array1)
print(result7)

[0 2 4 6 8]


[[ 0  2  4]
 [ 6  8 10]]


[ 0  2  4  6  8 10 13 15 17]


[0 1 3 5 7 9]


[[ 0  2  4]
 [ 6  8 10]
 [ 5  7  9]]


[[ 0  2  4  5  7  9]
 [ 6  8 10 13 15 17]]


[ 1  2  3  4  5  6  7  8  9 10]
